
export const EMAIL_CHANGE = "EMAIL_CHANGE";

export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_PENDING = "LOGIN_PENDING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_ERROR = "LOGIN_ERROR";